image: docker:19.03.8

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

services:
  - docker:19.03.8-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -v /var/run/docker.sock:/var/run/docker.sock -t kind-dind .
