image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -v /var/run/docker.sock:/var/run/docker.sock -t kind-dind .
