image: docker:19.03.8

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.8-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t kind-dind .
